version: '3.8'


services:
  web:
    build: .
    command: sh -c "python manage.py migrate --noinput &&
      python manage.py loaddata db_dump.json &&
      gunicorn --bind 0.0.0.0:8000 djangoTestsPerfomance.wsgi:application -w3"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

  db:
    image: postgres:latest
    container_name: back-db
    restart: always
    env_file:
     - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: back-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres:
  webapp:
